changelog:
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Docs and Examples
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - chore
        - dependencies
  exclude:
    labels:
      - skip-changelog
